name: cellcountenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ipywidgets=7.5.1
  - scikit-image=0.17.2
  - numpy=1.19.1
  - matplotlib=3.3.1
  - voila
  - jupyterlab=2.2.5
